name: Terraform - Hub

on:
  workflow_dispatch: {}

permissions:
  #id-token: write   # required for OIDC federated login
  contents: read
  pull-requests: write  # required to comment the plan on the PR

env:
  ARM_CLIENT_ID:  ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID_HUB }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  TF_STATE_RG: rg-tfstate-uaen-01
  TF_STATE_SA: sttfstateuaenor01
  TF_STATE_CONTAINER: tfstate
  TF_VAR_subscription_id:  ${{ secrets.AZURE_SUBSCRIPTION_ID_HUB }}

defaults:
  run:
    working-directory: /

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Azure secrets availability
        shell: bash
        run: |
          [ -n "$ARM_CLIENT_ID" ] && echo "ARM_CLIENT_ID is available" || echo "ARM_CLIENT_ID is EMPTY"
          [ -n "$ARM_TENANT_ID" ] && echo "ARM_TENANT_ID is available" || echo "ARM_TENANT_ID is EMPTY"
          [ -n "$ARM_SUBSCRIPTION_ID" ] && echo "ARM_SUBSCRIPTION_ID is available" || echo "ARM_SUBSCRIPTION_ID is EMPTY"
          [ -n "$ARM_CLIENT_SECRET" ] && echo "ARM_CLIENT_SECRET is available" || echo "ARM_CLIENT_SECRET is EMPTY"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      - name: Terraform init
        run: |
          terraform init \
            -backend-config="resource_group_name=${TF_STATE_RG}" \
            -backend-config="storage_account_name=${TF_STATE_SA}" \
            -backend-config="container_name=${TF_STATE_CONTAINER}"
